export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const LIST_TASK_REQUEST = 'LIST_TASK_REQUEST';

export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST';

export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST';

export const LIST_MINE_REQUEST = 'LIST_MINE_REQUEST';

export const CREATE_MINE_REQUEST = 'CREATE_MINE_REQUEST';

export const UPDATE_MINE_REQUEST = 'UPDATE_MINE_REQUEST';

export const REMOVE_MINE_REQUEST = 'REMOVE_MINE_REQUEST';
